# This is a basic workflow to help you get started with Actions

name: "Triage Issue"

# Controls when the action will run.
# Triggers the workflow when an issue is created or edited
on:
  issues:
    types: [opened, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  triage:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: RafaelKr/olive-issue-triage-bot@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
